### ISSUE TITLE
Transparent background (alpha) not working

### ISSUE THREAD

**Issue by jlangner-hubble** [vasturiano/react-force-graph#260] opened 2021-03-02 17:52 UTC
If I use the following example code, there is never a transparent background on the canvas. Is this possible anymore?

```jsx
<ForceGraph3D
    rendererConfig={{
	    alpha: true,
    }}
    backgroundColor={'rgba(0,0,0,0)'}
    ref={fgRef}
    graphData={data}
/>
```

Is the above code wrong or missing something? Is there a new / alternate way to do this?

**Comment by vasturiano** [comment] 2021-03-08 00:12
Duplicate of https://github.com/vasturiano/3d-force-graph/issues/437

**Closed by vasturiano** 2021-03-08 00:13 UTC
