### ISSUE TITLE
Attempted import error: 'Bezier' is not exported from 'bezier-js'

### ISSUE THREAD

**Issue by Fostefos** [vasturiano/react-force-graph#294] opened 2021-05-14 12:42 UTC
Error: Failed to Compile
Attempted import error: 'Bezier' is not exported from 'bezier-js'

1. npm install react-force-graph-2d
2. npm start

 - OS: Linux Ubuntu 20.04 (Focal Fossa)
 - Browser: Mozilla Firefox
 - npm version : 6.14.4
 - Node version : 10.19.0

Other depedencies :
"@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.11.2",
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "d3-force-3d": "^2.3.2",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-force-graph-2d": "^1.23.4",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.1"

**Comment by vasturiano** [comment] 2021-05-14 12:47
duplicate of https://github.com/vasturiano/react-force-graph/issues/282

**Closed by vasturiano** 2021-05-14 12:47 UTC
