### ISSUE TITLE
How can i add minimap for graph?

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/react-force-graph#511] opened 2024-04-29 11:14 UTC
**Is your feature request related to a problem? Please describe.**
I want to add minimap for my graph and see canvas objects if they are outside the canvas after zooming
I use this functionality and put the result inside src for image, but it provides only zoomed object. It doesn't includes objects outside zoom
``
canvas.toBlob(
                (blob) => {
                      onUpdateDataURL(blob)
                },
                'image/webp',
                0.7
            );
``
How can I solve it?
![image](https://github.com/vasturiano/react-force-graph/assets/23615115/0d100fcf-72a0-4dd9-85ff-4659b6ba7348)
![image](https://github.com/vasturiano/react-force-graph/assets/23615115/526306be-ecbb-48ea-b9b3-43cc184bde72)

**Describe the solution you'd like**
Minimap

**Comment by vasturiano** [comment] 2024-04-30 21:18
Duplicate of https://github.com/vasturiano/react-force-graph/issues/490

**Closed by vasturiano** 2024-04-30 21:18 UTC
