### ISSUE TITLE
Failed to execute getImageData issue on chrome

### ISSUE THREAD

**Issue by naumanzchaudhry** [vasturiano/react-force-graph#88] opened 2019-05-10 01:47 UTC
Hi, I am using ForceGraph2D to render my graph. It works real fine on every other browser but chrome is the exception. It produces the issue which can be seen in the below shot. 

![shot-for-issue](https://user-images.githubusercontent.com/15146710/57496898-b79fd900-72ee-11e9-83ea-932a69d99926.png)

Edit # 1: 

1) Same issue on Microsoft Edge as well. But edge shows `IndexSizeError` only instead of this descriptive error message. 

2) Canvas​Rendering​Context2D [docs](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage#Exceptions_thrown) on MDN describes it as 

> If the canvas or source rectangle width or height is zero.

@vasturiano can you please comment on it.

**Comment by vasturiano** [comment] 2019-05-10 07:37
@naumanzchaudhry I'm guessing you're not seeing that issue on a regular example, like this one: https://vasturiano.github.io/react-force-graph/example/custom-node-shape/index-canvas.html

Could you post a minimal example online that reproduces the issue?

**Comment by shaefer** [comment] 2019-05-10 19:43
I am also seeing this error. I can pretty confidently confirm that is is something that Chrome broke as my live production code was working (it is a reasonably simple example). It is now failing to run on Chrome producing the same error as above. Here is a link to my code: https://github.com/shaefer/dmscreen/blob/master/src/components/DungeonMapper/DungeonForceGraph2D.js

And a link to the live page: https://monsters.cleverorc.com/dungeongraph/8

**Comment by naumanzchaudhry** [comment] 2019-05-11 05:24
Hi @vasturiano @shaefer Thanks guys for taking your time out to comment. removing and reinstalling my dependencies worked for me. @shaefer check if that works for you as well.

**Comment by davidballester** [comment] 2019-05-11 11:28
> Removing and reinstalling my dependencies worked for me.

Sadly, that didn't work for me. I didn't have the time to look into the root cause of the issue, but managed to find a workaround it, though: patch `force-graph.module.js`, like this:

```diff
diff --git a/node_modules/force-graph/dist/force-graph.module.js b/node_modules/force-graph/dist/force-graph.module.js
index 4c312a8..025b93b 100644
--- a/node_modules/force-graph/dist/force-graph.module.js
+++ b/node_modules/force-graph/dist/force-graph.module.js
@@ -1171,8 +1171,8 @@ var forceGraph = Kapsule({
     container.appendChild(toolTipElem); // Capture mouse coords on move
 
     var mousePos = {
-      x: -1e12,
-      y: -1e12
+      x: 0,
+      y: 0
     };
     state.canvas.addEventListener('mousemove', function (ev) {
       // update the mouse pos
```

**Comment by vasturiano** [comment] 2019-05-11 20:32
This is an issue that was fixed in the [force-graph](https://github.com/vasturiano/force-graph) module from version `1.14.4`. This is the patch fix:
https://github.com/vasturiano/force-graph/commit/9f37baa276c9cc30779b6b33ae9e86782660dcf6

If you're experiencing this issue please look in your dependency tree and make sure you're using a version of `force-graph` more recent than `1.14.4`.

**Comment by shaefer** [comment] 2019-05-12 22:27
I pushed a new version that 1.6.1 and everything is looking great. (It looked like I *should have been* on 1.5.1 before. However, I didn't check for certain what version was actually pulled in for the deployed app since the update fixed everything, so I am going to assume I just had an older version that hadn't addressed the issue. Thanks for looking into things and responding! @vasturiano

**Comment by davidballester** [comment] 2019-05-13 17:35
I was on 1.14.3, I think (in any case, previous to 1.14.4). Updating the package to 1.15.0 solved the issue for me. 🎈

**Closed** 2019-05-17 05:46 UTC
