### ISSUE TITLE
Incorrect Node Label displayed

### ISSUE THREAD

**Issue by joshraymo** [vasturiano/react-force-graph#418] opened 2023-01-23 23:54 UTC
**Describe the bug**
There seems to be a bug where the incorrect node is passed to our nodeLabel function on mouse over.  As you can see in the attached video, it only occurs when hovering over the outer border.

**To Reproduce**
1. Hover 

**Expected behavior**
The nodeLabel behavior should not display the incorrect node information

**Desktop (please complete the following information):**
 - IOS/Chrome

**Smartphone (please complete the following information):**

**Additional context**
We are using a custom function passed to nodeLabel that injects an html template string

**Comment by vasturiano** [comment] 2023-01-28 19:35
Duplicate of https://github.com/vasturiano/force-graph/issues/303

**Closed by vasturiano** 2023-01-28 19:35 UTC
