### ISSUE TITLE
Question: For nodes with HTML in them, is there a way for the user to select the HTML elements that are rendered?

### ISSUE THREAD

**Issue by drewrh** [vasturiano/react-force-graph#382] opened 2022-06-22 02:48 UTC
I'm 90% sure that the answer is "no" but I wanted to ask here to see if I could get a definite answer.

As seen in the [HTML in nodes](https://vasturiano.github.io/react-force-graph/example/html-nodes/) example, it is possible to render HTML. Is it possible for the user to select the HTML that is rendered on the node, or if what is rendered is only a image.

I tried reading through the [documentation of the CSS2DRenderer object](https://github.com/mrdoob/three.js/blob/master/examples/jsm/renderers/CSS2DRenderer.js) that is being used in the example, but it's a little over my head.

Any help or information would be much appreciated, thanks!

**Comment by vasturiano** [comment] 2022-06-22 22:28
Duplicate of https://github.com/vasturiano/3d-force-graph/issues/552.

**Closed by vasturiano** 2022-06-22 22:28 UTC
